logFilters:
  - level: discard
    pattern: '*@npm:* The darwin-* architecture'

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  '@chakra-ui/anatomy@*':
    dependencies:
      '@chakra-ui/system': '*'
      react: '*'
  '@chakra-ui/checkbox@*':
    dependencies:
      framer-motion: '*'
      react-dom: '*'
  '@chakra-ui/props-docs@*':
    dependencies:
      '@emotion/react': '*'
      '@emotion/styled': '*'
      framer-motion: '*'
      react: '*'
      react-dom: '*'
      typescript: '*'
  '@chakra-ui/skeleton@*':
    dependencies:
      '@chakra-ui/theme': '*'
  '@chakra-ui/system@*':
    dependencies:
      '@emotion/react': '*'
      '@emotion/styled': '*'
  '@chakra-ui/transition@*':
    dependencies:
      framer-motion: '*'
      react-dom: '*'
