logFilters:
  - level: discard
    pattern: '*@npm:* The darwin-* architecture'

nodeLinker: node-modules

npmScopes:
  saas-ui:
    npmRegistryServer: 'https://npm.saas-ui.dev'
npmRegistries:
  //npm.saas-ui.dev:
    npmAuthIdent: '${SAAS_UI_TOKEN:-}'
    npmAlwaysAuth: true

packageExtensions:
  '@chakra-ui/props-docs@*':
    peerDependencies:
      '@emotion/react': '*'
      '@emotion/styled': '*'
      'framer-motion': '*'
      'react': '*'
      'react-dom': '*'
      'typescript': '*'
  '@chakra-ui/cli@*':
    peerDependencies:
      '@types/node': '*'
      typescript: '*'
  '@chakra-ui/toast@*':
    peerDependencies:
      '@emotion/react': '*'
      '@emotion/styled': '*'
  '@storybook/cli@*':
    peerDependencies:
      'react': '*'
      'react-dom': '*'
      'typescript': '*'
  '@storybook/codemod@*':
    peerDependencies:
      '@babel/preset-env': '*'
  '@storybook/docs-tools@*':
    peerDependencies:
      'react': '*'
      'react-dom': '*'
  '@storybook/mdx1-csf@*':
    peerDependencies:
      '@babel/core': '*'
  '@storybook/telemetry@*':
    peerDependencies:
      'react': '*'
      'react-dom': '*'
  '@swc-node/jest@*':
    peerDependencies:
      typescript: '*'
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
