yarnPath: .yarn/releases/yarn-3.1.1.cjs
nodeLinker: node-modules

logFilters:
  - pattern: '@next/swc-*@npm:* The darwin-x64 architecture is incompatible with this module, link skipped.'
    level: discard
  - pattern: 'esbuild-*@npm:* The darwin-x64 architecture is incompatible with this module, link skipped.'
    level: discard

packageExtensions:
  '@chakra-ui/anatomy@*':
    dependencies:
      '@chakra-ui/system': '*'
      'react': '*'
  '@chakra-ui/props-docs@*':
    dependencies:
      '@emotion/react': '*'
      '@emotion/styled': '*'
      'react': '*'
      'react-dom': '*'
      'framer-motion': '*'
      'typescript': '*'
  '@chakra-ui/skeleton@*':
    dependencies:
      '@chakra-ui/theme': '*'
  '@chakra-ui/system@*':
    dependencies:
      '@emotion/react': '*'
      '@emotion/styled': '*'
  '@chakra-ui/checkbox@*':
    dependencies:
      'react-dom': '*'
      'framer-motion': '*'
  '@chakra-ui/transition@*':
    dependencies:
      'framer-motion': '*'
      'react-dom': '*'
