[build]
  command = "yarn build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/_next/static/*"
to = "/static/:splat"
status = 200

[[redirects]]
from = "/_next/image*"
to = "/_ipx/w_:width,q_:quality/:url"
status = 301
query = { url = ":url", w = ":width", q = ":quality" }

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/builders/_ipx"
status = 200

[[redirects]]
from = "/cache/*"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/server/*"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/serverless/*"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/traces"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/routes-manifest.json"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/build-manifest.json"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/prerender-manifest.json"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/react-loadable-manifest.json"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/BUILD_ID"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/api"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/404 Error-pana.svg"
to = "/404 Error-pana.svg"
status = 200
conditions = {Cookie = []}


[[redirects]]
from = "/Launching-amico.svg"
to = "/Launching-amico.svg"
status = 200
conditions = {Cookie = []}


[[redirects]]
from = "/app.png"
to = "/app.png"
status = 200
conditions = {Cookie = []}

[[redirects]]
from = "/blog.xml"
to = "/blog.xml"
status = 200
conditions = {Cookie = []}


[[redirects]]
from = "/chakra-ui-logomark-colored.svg"
to = "/chakra-ui-logomark-colored.svg"
status = 200
conditions = {Cookie = []}


[[redirects]]
from = "/docs.xml"
to = "/docs.xml"
status = 200
conditions = {Cookie = []}


[[redirects]]
from = "/eelco.jpg"
to = "/eelco.jpg"
status = 200
conditions = {Cookie = []}


[[redirects]]
from = "/eelco128.jpg"
to = "/eelco128.jpg"
status = 200
conditions = {Cookie = []}


[[redirects]]
from = "/favicon.ico"
to = "/favicon.ico"
status = 200
conditions = {Cookie = []}


[[redirects]]
from = "/icon.png"
to = "/icon.png"
status = 200
conditions = {Cookie = []}

[[redirects]]
from = "/manifest.json"
to = "/manifest.json"
status = 200
conditions = {Cookie = []}


[[redirects]]
from = "/saasui-dark.svg"
to = "/saasui-dark.svg"
status = 200
conditions = {Cookie = []}


[[redirects]]
from = "/saasui.svg"
to = "/saasui.svg"
status = 200
conditions = {Cookie = []}


[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200
conditions = {Cookie = []}


[[redirects]]
from = "/frameworks/bedrock.svg"
to = "/frameworks/bedrock.svg"
status = 200
conditions = {Cookie = []}

[[redirects]]
from = "/frameworks/blitz.svg"
to = "/frameworks/blitz.svg"
status = 200
conditions = {Cookie = []}


[[redirects]]
from = "/frameworks/nextjs.svg"
to = "/frameworks/nextjs.svg"
status = 200
conditions = {Cookie = []}

[[redirects]]
from = "/frameworks/redwood.svg"
to = "/frameworks/redwood.svg"
status = 200
conditions = {Cookie = []}

[[redirects]]
from = "/frameworks/supabase.svg"
to = "/frameworks/supabase.svg"
status = 200
conditions = {Cookie = []}

[[redirects]]
from = "/frameworks/ts-logo-512.svg"
to = "/frameworks/ts-logo-512.svg"
status = 200
conditions = {Cookie = []}

[[redirects]]
from = "/img/portugal.jpg"
to = "/img/portugal.jpg"
status = 200
conditions = {Cookie = []}

[[redirects]]
from = "/*"
to = "/.netlify/functions/___netlify-handler"
status = 200
force = true
conditions = {Cookie = []}

[[redirects]]
from = "/_next/data/GcDe4NhzcejATFPXKcVyD/404.json"
to = "/.netlify/functions/___netlify-handler"
status = 200
force = false

[[redirects]]
from = "/404"
to = "/.netlify/functions/___netlify-handler"
status = 200
force = false

[[redirects]]
from = "/_next/data/GcDe4NhzcejATFPXKcVyD/privacy.json"
to = "/.netlify/functions/___netlify-handler"
status = 200
force = false

[[redirects]]
from = "/privacy"
to = "/.netlify/functions/___netlify-handler"
status = 200
force = false

[[redirects]]
from = "/_next/data/GcDe4NhzcejATFPXKcVyD/blog/:slug/*"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200
force = false

[[redirects]]
from = "/blog/:slug/*"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200
force = false

[[redirects]]
from = "/_next/data/GcDe4NhzcejATFPXKcVyD/docs.json"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200
force = false

[[redirects]]
from = "/_next/data/GcDe4NhzcejATFPXKcVyD/docs/*"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200
force = false

[[redirects]]
from = "/docs"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200
force = false

[[redirects]]
from = "/docs/*"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200
force = false

[[redirects]]
from = "/*"
to = "/.netlify/functions/___netlify-handler"
status = 200
